# Conda environment file for Fashion Shopping Assistant
# This ensures better compatibility across different systems

name: fashion-assistant
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  # Core scientific packages
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.1

  # Image processing
  - pillow=10.0.0
  - opencv=4.8.0

  # Machine learning
  - scikit-learn=1.3.0

  # Deep learning (PyTorch)
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cpuonly  # Remove this line if you have CUDA

  # Visualization
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0

  # Utilities
  - tqdm=4.65.0
  - requests=2.31.0
  - python-dotenv=1.0.0

  # Jupyter support
  - jupyter=1.0.0
  - ipywidgets=8.0.7

  # Pip dependencies (install via pip after conda)
  - pip
  - pip:
    # Web framework
    - streamlit==1.28.1

    # FAISS for similarity search
    - faiss-cpu==1.7.4

    # Kaggle API
    - kaggle==1.5.16
